name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run Update Python Script
      run: |
        python script/count_files.py
    - name: Run Update README.md File
      run: |
        git add .
        git diff
        git config --local user.email "ddingminyt@gmail.com"
        git config --local user.name "ddingmin"
        git commit -m ":smile Add Today I Learned"
        git push